---
sidebar: sidebar 
permalink: scpivs44_configure_credentials_for_vm_guest_file_restores.html 
keywords:  
summary: Quando si collega un disco virtuale per le operazioni di ripristino di file guest o cartelle, la macchina virtuale di destinazione per il collegamento deve avere le credenziali configurate prima del ripristino. 
---
= Configurare le credenziali per il ripristino del file guest della macchina virtuale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si collega un disco virtuale per le operazioni di ripristino di file guest o cartelle, la macchina virtuale di destinazione per il collegamento deve avere le credenziali configurate prima del ripristino.

.A proposito di questa attività
La tabella seguente elenca i requisiti delle credenziali per le operazioni di ripristino guest.

|===
|  | Controllo dell'accesso dell'utente attivato | Controllo dell'accesso dell'utente disattivato 


| Utente di dominio | Un utente di dominio con "amministratore" come nome utente funziona correttamente. Ad esempio, "NetApp/Administrator". Tuttavia, un utente di dominio con "xyz" come nome utente appartenente a un gruppo di amministratori locale non funzionerà. Ad esempio, non è possibile utilizzare "NetApp". | Un utente di dominio con "amministratore" come nome utente o un utente di dominio con "xyz" come nome utente che appartiene a un gruppo di amministratori locale funziona correttamente. Ad esempio, "NetApp" o "NetApp". 


| Utente di Workgroup | Un utente locale con "amministratore" come nome utente funziona correttamente. Tuttavia, un utente locale con "xyz" come nome utente appartenente a un gruppo di amministratori locale non funzionerà. | Un utente locale con "amministratore" come nome utente o un utente locale con "xyz" come nome utente che appartiene a un gruppo di amministratori locale funziona correttamente. Tuttavia, un utente locale con "xyz" come nome utente che non appartiene al gruppo di amministratori locale non funzionerà. 
|===
Negli esempi precedenti, "NetApp" è il nome di dominio fittizio e "xyz" è il nome utente locale fittizio

.Fasi
. Dalla finestra dei collegamenti client vSphere, selezionare *plug-in SnapCenter per VMware vSphere* in plug-in.
. Nella barra di navigazione a sinistra, selezionare *Ripristino file guest*.
. Nella sezione *Esegui come credenziali*, eseguire una delle seguenti operazioni:
+
|===
| A tal fine… | Eseguire questa operazione… 


| Utilizzare le credenziali esistenti | Selezionare una delle credenziali configurate. 


| Aggiungere nuove credenziali  a| 
.. Selezionare *Aggiungi*.
.. Nella finestra di dialogo *Esegui come credenziali*, immettere le credenziali. Per Nome utente, immettere "Amministratore".
.. Fare clic su *Select VM*, quindi selezionare una VM nella finestra di dialogo *Proxy VM*. Fare clic su *Save* (Salva) per tornare alla finestra di dialogo *Run as Credentials* (Esegui come credenziali). Selezionare la VM da utilizzare per autenticare le credenziali.


|===
+
Il plug-in SnapCenter per VMware vSphere utilizza le credenziali selezionate per accedere alla VM selezionata.

. Fare clic su *Save* (Salva).

