---
sidebar: sidebar 
permalink: scpivs44_rest_apis__download_jobs_and_generate_reports.html 
keywords:  
summary: Per generare report e scaricare log per i processi del client VMware vSphere utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario utilizzare le chiamate API REST per VMware vSphere. 
---
= API REST per scaricare i lavori e generare report
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per generare report e scaricare log per i processi del client VMware vSphere utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario utilizzare le chiamate API REST per VMware vSphere.

Per ogni API REST, aggiungere `https://<server>:<port>` All'inizio dell'API REST per formare un endpoint completo.



== Utilizzare le seguenti API REST nella sezione lavori per ottenere informazioni dettagliate sui lavori:

|===
| API REST | Commenti 


| `/4.1/jobs` | `Get all jobs` ottiene i dettagli del lavoro per più lavori. È possibile limitare l'ambito della richiesta specificando un tipo di lavoro, ad esempio `backup`, `mountBackup`, o. `restore`. 


| `/4.1/jobs/{id}` | `Get job details` ottiene informazioni dettagliate per il lavoro specificato. 
|===


== Utilizzare la seguente API REST nella sezione lavori per scaricare i log dei lavori:

|===
| API REST | Commenti 


| `/4.1/jobs/{id}/logs` | `getJobLogsById` scarica i log per il lavoro specificato. 
|===


== Utilizzare le seguenti API REST nella sezione Report per generare i report:

|===
| API REST | Commenti 


| `4.1/reports/protectedVM` | `Get Protected VM List` Ottiene un elenco delle macchine virtuali protette durante gli ultimi sette giorni. 


| `/4.1/reports/
unProtectedVM` | `Get Unprotected VM List` Ottiene un elenco delle macchine virtuali non protette durante gli ultimi sette giorni. 
|===