---
sidebar: sidebar 
permalink: scpivs44_rest_api_workflow__restore_vms.html 
keywords:  
summary: Per eseguire operazioni di ripristino per i backup delle macchine virtuali utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario seguire la sequenza prescritta di chiamate API REST. 
---
= Workflow API REST per il ripristino delle macchine virtuali
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per eseguire operazioni di ripristino per i backup delle macchine virtuali utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario seguire la sequenza prescritta di chiamate API REST.

Per ogni API REST, aggiungere `https://<server>:<port>` All'inizio dell'API REST per formare un endpoint completo.

|===
| Fase | API REST | Commenti 


| 1 | Passare a. `http://<vCenter-IP>/mob` | Individuare il moref delle macchine virtuali dall'URL VMware Managed Objects. Notare il *moref* della macchina virtuale che si desidera ripristinare. 


| 2 | `/4.1/vm/{moref}/backups` | `Get VM Backups` Ottiene un elenco di backup per la macchina virtuale specificata. Passare il *moref* del passaggio 1. Annotare il *backupId* del backup che si desidera ripristinare. 


| 3 | `/4.1/vm/backups/{backupId}/
snapshotlocations` | `Get snapshot locations` Ottiene la posizione della copia Snapshot per il backup specificato. Passare il *backupId* del passaggio 2. Annotare le informazioni *snapshotLocationsList*. 


| 4 | `/4.1/vm/{moref}/backups/
availableesxhosts` | `Get available ESX Hosts` ottiene le informazioni per l'host su cui è memorizzato il backup. Annotare le informazioni *AvailableEsxHostsList*. 


| 5 | `/4.1/vm/{moref}/backups/
{backupId}/restore`  a| 
`Restore a VM from a backup` ripristina il backup specificato. Passare le informazioni dei passaggi 3 e 4 nell'attributo *restoreLocations*.


NOTE: Se il backup della macchina virtuale è un backup parziale, impostare `restartVM` parametro su "false".


NOTE: Non è possibile ripristinare una macchina virtuale che è un modello.

|===