---
sidebar: sidebar 
permalink: scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere_01.html 
keywords:  
summary:  
---
= Implementare il plug-in SnapCenter per VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per utilizzare le funzionalità di SnapCenter per proteggere macchine virtuali, datastore e database coerenti con le applicazioni su macchine virtualizzate, è necessario implementare il plug-in SnapCenter per VMware vSphere.
Il link:scpivs44_download_the_ova_open_virtual_appliance.html["Scarica Open Virtual Appliance (OVA)"^] Fornisce istruzioni per scaricare i file OVA.

. Per VMware vCenter 7.0.3 e versioni successive, seguire la procedura descritta in link:scpivs44_download_the_ova_open_virtual_appliance.html["Scarica Open Virtual Appliance (OVA)"^] Per importare i certificati in vCenter.
. Nel browser, accedere a VMware vSphere vCenter.
+

NOTE: Per i client Web IPv6 HTML, è necessario utilizzare Chrome o Firefox.

. Accedere alla pagina *VMware vCenter Single Sign-on*.
. Nel riquadro di navigazione, fare clic con il pulsante destro del mouse su qualsiasi oggetto di inventario che sia un oggetto padre valido di una macchina virtuale, ad esempio un data center, una cartella, un cluster o un host, quindi selezionare *Deploy OVF Template* (implementa modello OVF) per avviare la procedura guidata di implementazione di VMware.
. Nella pagina *Select an OVF template* (Seleziona un modello OVF), specificare la posizione di `.ova` (Come elencato nella tabella seguente) e fare clic su *Avanti*.
+
|===
| In questa pagina della procedura guidata… | Eseguire questa operazione… 


| Selezionare un nome e una cartella | Immettere un nome univoco per la macchina virtuale o la vApp e selezionare una posizione di implementazione. 


| Selezionare una risorsa | Selezionare una risorsa in cui si desidera eseguire il modello di macchina virtuale distribuito. 


| Rivedere i dettagli | Verificare `.ova` dettagli del modello. 


| Contratti di licenza | Selezionare la casella di controllo *Accetto tutti i contratti di licenza*. 


| Selezionare lo storage | Definire dove e come memorizzare i file per il modello OVF distribuito. 


| Selezionare reti | Selezionare una rete di origine e associarla a una rete di destinazione. 


| Personalizzare il modello  a| 
In *Register to existing vCenter* (Registra su vCenter esistente), immettere le credenziali vCenter. In *Crea plug-in SnapCenter per le credenziali VMware vSphere*, immettere il plug-in SnapCenter per le credenziali VMware vSphere.


NOTE: Annotare il nome utente e la password specificati. È necessario utilizzare queste credenziali se si desidera modificare in un secondo momento la configurazione del plug-in SnapCenter per VMware vSphere.

Nella sezione *impostazione delle proprietà di rete*, immettere le informazioni di rete. Nella sezione *impostazione data e ora*, selezionare il fuso orario in cui si trova vCenter.



| Pronto per essere completato | Esaminare la pagina e fare clic su *fine*. 
|===
+

NOTE: Tutti gli host devono essere configurati con indirizzi IP (i nomi host FQDN non sono supportati). L'operazione di implementazione non convalida l'input prima dell'implementazione.

. Passare alla VM in cui è stato distribuito il plug-in SnapCenter per VMware vSphere, quindi fare clic sulla scheda *Riepilogo*, quindi fare clic sulla casella *accensione* per avviare il plug-in SnapCenter per VMware vSphere.
. Durante l'accensione del plug-in SnapCenter per VMware vSphere, fare clic con il pulsante destro del mouse sul plug-in SnapCenter per VMware vSphere distribuito, selezionare *guest OS*, quindi fare clic su *Install VMware Tools*.
+
Il completamento dell'implementazione potrebbe richiedere alcuni minuti. La distribuzione corretta è indicata quando il plug-in SnapCenter per VMware vSphere viene acceso, quando vengono installati gli strumenti VMware e la schermata richiede di accedere al plug-in SnapCenter per VMware vSphere.

+
La schermata visualizza l'indirizzo IP in cui viene distribuito il plug-in SnapCenter per VMware vSphere. Annotare l'indirizzo IP. Se si desidera modificare la configurazione del plug-in SnapCenter per VMware vSphere, è necessario accedere alla GUI di gestione del plug-in SnapCenter per VMware vSphere.

. Accedere alla GUI di gestione del plug-in SnapCenter per VMware vSphere utilizzando l'indirizzo IP visualizzato nella schermata di distribuzione utilizzando le credenziali fornite nella procedura guidata di distribuzione, quindi verificare sulla dashboard che il plug-in SnapCenter per VMware vSphere sia connesso correttamente a vCenter e sia abilitato.
+
Utilizzare il formato `\https://<appliance-IP-address>:8080` Per accedere alla GUI di gestione.

+
Accedere con il nome utente e la password dell'amministratore impostati al momento dell'implementazione e il token MFA generato dalla console di manutenzione.

. Accedere al client vCenter HTML5, fare clic su *Menu* nella barra degli strumenti, quindi selezionare *plug-in SnapCenter per VMware vSphere*

