---
sidebar: sidebar 
permalink: scpivs44_create_backup_policies_for_vms_and_datastores.html 
keywords:  
summary: È necessario creare policy di backup prima di utilizzare il plug-in SnapCenter per VMware vSphere per eseguire il backup di macchine virtuali e datastore. 
---
= Creare policy di backup per macchine virtuali e datastore
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È necessario creare policy di backup prima di utilizzare il plug-in SnapCenter per VMware vSphere per eseguire il backup di macchine virtuali e datastore.

.Prima di iniziare
* È necessario aver letto i prerequisiti.
* È necessario configurare le relazioni di storage secondario.
+
** Se si stanno replicando snapshot in uno storage secondario mirror o vault, è necessario configurare le relazioni e assegnare le VM di storage all'amministratore SnapCenter sia per i volumi di origine che di destinazione.
** Per trasferire correttamente le snapshot nello storage secondario per le relazioni Version-FlexibleMirror in un datastore NFS o VMFS, verificare che il tipo di policy SnapMirror sia Asynchronous Mirror e che l'opzione "All_source_Snapshots" sia selezionata.
** Quando il numero di snapshot sullo storage secondario (mirror-vault) raggiunge il limite massimo, l'attività di registrazione del backup e di applicazione della conservazione nell'operazione di backup non riesce e viene visualizzato il seguente errore: `This snapshot is currently used as a reference snapshot by one or more SnapMirror relationships. Deleting the snapshot can cause future SnapMirror operations to fail.`
+
Per correggere questo problema, configurare il criterio di conservazione SnapMirror per lo storage secondario in modo da evitare di raggiungere il limite massimo di snapshot.

+
Per informazioni su come gli amministratori assegnano le risorse agli utenti, fare riferimento a https://docs.netapp.com/us-en/snapcenter/get-started/rbac-snapcenter.html["Informazioni SnapCenter sull'utilizzo del controllo degli accessi basato sui ruoli"^] .



* Se si desidera eseguire backup coerenti con le macchine virtuali, è necessario disporre dei tool VMware installati e in esecuzione. I tool VMware sono necessari per interrompere le macchine virtuali. I backup coerenti con le macchine virtuali non sono supportati per le macchine virtuali vVol.
* SnapMirror Active Sync consente ai servizi di business di continuare a funzionare anche in caso di guasto completo del sito, supportando le applicazioni per il failover in modo trasparente con una copia secondaria.
+

NOTE: La sincronizzazione attiva di SnapMirror è supportata solo per datastore VMFS.

+
Per proteggere un datastore VMFS su un'implementazione con sincronizzazione attiva SnapMirror, come amministratore SnapCenter devi:

+
** Configurare i cluster e il mediatore come descritto nel report tecnico: https://docs.netapp.com/us-en/ontap/snapmirror-active-sync/mediator-install-task.html["Configurare ONTAP Mediator e i cluster per la sincronizzazione attiva di SnapMirror"].
** Aggiungi il volume associato al datastore VMFS al gruppo di coerenza e crea una relazione di data Protection utilizzando la policy di protezione _AutomatedFailOver_ o _AutomatedFailOverDuplex_ tra due sistemi storage ONTAP. Il criterio _AutomatedFailOverDuplex_ è supportato a partire da ONTAP 9.15.1.





NOTE: Nella configurazione fan-out, il gruppo di coerenza non è supportato per il terzo sito.

.A proposito di questa attività
La maggior parte dei campi presenti in queste pagine della procedura guidata sono esplicativi. Le seguenti informazioni descrivono alcuni dei campi per i quali potrebbe essere necessaria una guida.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *Criteri*.
. Nella pagina *Criteri*, selezionare *Crea* per avviare la procedura guidata.
. Nella pagina *New Backup Policy* (nuovo criterio di backup), immettere il nome del criterio e una descrizione.
+
** Linked mode (modalità collegata
+
In modalità Linked, ogni vCenter dispone di un'appliance virtuale separata. Pertanto, è possibile utilizzare nomi duplicati nei vCenter. Tuttavia, è necessario creare il criterio nello stesso vCenter del gruppo di risorse.

** Caratteri non supportati
+
Non utilizzare i seguenti caratteri speciali in VM, datastore, cluster, policy, backup, o nomi di gruppi di risorse: % e * n. @ ! / : * ? " < > - | ; ' e spazio.

+
È consentito un carattere di sottolineatura (_).



. Specificare le impostazioni della frequenza.
+
Il criterio specifica solo la frequenza di backup. La pianificazione di protezione specifica per il backup viene definita nel gruppo di risorse. Pertanto, due o più gruppi di risorse possono condividere la stessa policy e la stessa frequenza di backup, ma hanno diverse pianificazioni di backup.

. Selezionare la casella di controllo *periodo di blocco* per attivare il blocco delle istantanee. È possibile selezionare i periodi di blocco dello snapshot primario e secondario come giorni/mesi/anni.
+

NOTE: Indipendentemente dal valore di conservazione impostato nel criterio ONTAP SnapMirror, la copia dello snapshot secondario non viene eliminata prima del periodo di blocco dello snapshot secondario specificato.

. Specificare le impostazioni di conservazione.
+

IMPORTANT: Se si prevede di attivare la replica SnapVault, è necessario impostare il numero di conservazione su 2 backup o su un valore superiore. Se si imposta il conteggio di conservazione su 1 backup da mantenere, l'operazione di conservazione potrebbe non riuscire. Questo perché il primo snapshot è lo snapshot di riferimento per la relazione SnapVault fino a quando lo snapshot più recente non viene replicato sulla destinazione.

+

NOTE: Il valore massimo di conservazione è 1018 backup. I backup non avranno esito positivo se la conservazione viene impostata su un valore superiore a quello supportato dalla versione di ONTAP sottostante. Ciò vale anche per gli archivi dati di spanning.



. Nei campi *Replication*, specificare il tipo di replica sullo storage secondario, come mostrato nella tabella seguente:
+
|===
| Per questo campo… | Eseguire questa operazione… 


| Aggiornare SnapMirror dopo il backup  a| 
Selezionare questa opzione per creare copie mirror dei set di backup su un altro volume che ha una relazione SnapMirror con il volume di backup primario. Se un volume è configurato con una relazione di vault mirror, selezionare solo l'opzione *Aggiorna SnapVault dopo il backup* se si desidera copiare i backup nelle destinazioni del vault mirror.


NOTE: Questa opzione è supportata per i datastore nei volumi FlexGroup nel plug-in SnapCenter per VMware vSphere 4.5 e versioni successive.


NOTE: Per proteggere il datastore VMFS sulla distribuzione Active Sync di SnapMirror, è necessario completare i prerequisiti indicati nella sezione _prima di iniziare_ e abilitare *Update SnapMirror after backup*.



| Aggiornare SnapVault dopo il backup  a| 
Selezionare questa opzione per eseguire la replica del backup disk-to-disk su un altro volume che ha una relazione SnapVault con il volume di backup primario.


IMPORTANT: Se un volume è configurato con una relazione di vault mirror, selezionare solo questa opzione se si desidera copiare i backup nelle destinazioni del vault mirror.


NOTE: Questa opzione è supportata per i datastore nei volumi FlexGroup nel plug-in SnapCenter per VMware vSphere 4.5 e versioni successive.



| Etichetta Snapshot  a| 
Immettere un'etichetta opzionale personalizzata da aggiungere agli snapshot SnapVault e SnapMirror creati con questo criterio. L'etichetta consente di distinguere le snapshot create con questa policy da quelle presenti nel sistema di storage secondario.


NOTE: È consentito un massimo di 31 caratteri per le etichette delle istantanee.

|===
. Facoltativo: Nei campi *Avanzate*, selezionare i campi necessari. I dettagli dei campi avanzati sono elencati nella seguente tabella.
+
|===
| Per questo campo… | Eseguire questa operazione… 


| Coerenza delle macchine virtuali  a| 
Selezionare questa casella per interrompere le macchine virtuali e creare uno snapshot VMware ogni volta che viene eseguito il processo di backup.

Questa opzione non è supportata per vVol. Per le VM vVol, vengono eseguiti solo backup coerenti con il crash.


IMPORTANT: Per eseguire backup coerenti con le macchine virtuali, è necessario disporre degli strumenti VMware in esecuzione sulla macchina virtuale. Se gli strumenti VMware non sono in esecuzione, viene eseguito un backup coerente con il crash.


NOTE: Quando si seleziona la casella coerenza delle macchine virtuali, le operazioni di backup potrebbero richiedere più tempo e più spazio di storage. In questo scenario, le macchine virtuali vengono prima bloccate, quindi VMware esegue uno snapshot coerente delle macchine virtuali, quindi SnapCenter esegue l'operazione di backup e le operazioni delle macchine virtuali vengono ripristinati. La memoria guest delle VM non è inclusa negli snapshot di coerenza delle VM.



| Includi datastore con dischi indipendenti | Selezionare questa casella per includere nel backup eventuali datastore con dischi indipendenti che contengono dati temporanei. 


| Script  a| 
Immettere il percorso completo del file postscript o del file richiesto che si desidera venga eseguito prima o dopo le operazioni di backup dal plug-in SnapCenter per VMware vSphere. Ad esempio, è possibile eseguire uno script per aggiornare i trap SNMP, automatizzare gli avvisi e inviare i registri. Il percorso dello script viene convalidato al momento dell'esecuzione dello script.


NOTE: Le prescritture e i post-script devono essere posizionati sulla macchina virtuale dell'appliance. Per inserire più script, premere *Invio* dopo ogni percorso di script per elencare ciascuno script su una riga separata. Il carattere ";" non è consentito.

|===
. Selezionare *Aggiungi.*
+
È possibile verificare che il criterio sia stato creato e rivedere la configurazione del criterio selezionando il criterio nella pagina Criteri.


