---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: Dopo aver aggiornato il plug-in SnapCenter per VMware vSphere a una nuova patch della stessa release, i job recenti o altre informazioni potrebbero non essere visualizzati nella dashboard e nel monitor dei processi. 
---
= Informazioni non visualizzate dopo l'aggiornamento a una nuova patch della stessa release
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver aggiornato il plug-in SnapCenter per VMware vSphere a una nuova patch della stessa release, i job recenti o altre informazioni potrebbero non essere visualizzati nella dashboard e nel monitor dei processi.

Se si esegue l'aggiornamento a una nuova patch della stessa release, è necessario cancellare la cache del plug-in SnapCenter per VMware vSphere sul server Web vCenter e riavviare il server prima dell'aggiornamento o della registrazione.

Se la cache del plug-in non viene cancellata, i job recenti non vengono visualizzati nella dashboard e nel monitor dei job nei seguenti scenari:

* Il plug-in SnapCenter per VMware vSphere è stato implementato utilizzando vCenter e successivamente aggiornato a una patch nella stessa release.
* L'appliance virtuale VMware di SnapCenter è stata implementata in vCenter 1. In seguito, questo plug-in SnapCenter per VMware vSphere è stato registrato al nuovo vCenter2. Viene creata una nuova istanza del plug-in SnapCenter per VMware vSphere con una patch e registrata su vCenter1. Tuttavia, poiché vCenter1 ha ancora il plug-in memorizzato nella cache del primo plug-in SnapCenter per VMware vSphere senza la patch, è necessario cancellare la cache.


La cache si trova nelle seguenti posizioni, in base al tipo di sistema operativo del server:

* Appliance vCenter Server Linux
+
`/etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity/`

* Sistema operativo Windows
+
`%PROGRAMFILES%/VMware/vSphere client/vc-packages/vsphere-client-serenity/`





== Soluzione alternativa se è già stato eseguito l'aggiornamento prima di svuotare la cache

. Accedere all'interfaccia grafica di gestione del plug-in SnapCenter per VMware vSphere.
+
L'indirizzo IP viene visualizzato quando si implementa il plug-in SnapCenter per VMware vSphere.

. Fare clic su *Configuration* nel riquadro di navigazione a sinistra, quindi fare clic sull'opzione Service (Servizio) nella sezione *Plug-in Details* (Dettagli plug-in) per disattivare il plug-in.
+
Il plug-in SnapCenter per il servizio VMware vSphere è disattivato e l'estensione non è registrata in vCenter.

. Individuare il `vsphere-client-serenity` quindi individuare `com.netapp.scv.client-<release-number>` ed eliminarla.
+
Il nome della cartella cambia per ogni release.

. Riavviare vCenter Server.
. Accedere al client VMware vSphere.
. Fare clic su *Configuration* nel riquadro di navigazione a sinistra, quindi fare clic sull'opzione Service (Servizio) nella sezione *Plug-in Details* (Dettagli plug-in) per attivare il plug-in.
+
Il plug-in SnapCenter per il servizio VMware vSphere è abilitato e l'estensione è registrata in vCenter.


