---
sidebar: sidebar 
permalink: scpivs44_add_a_single_vm_or_datastore_to_a_resource_group.html 
keywords:  
summary: Puoi aggiungere rapidamente una singola macchina virtuale o un datastore a qualsiasi gruppo di risorse esistente gestito dal plug-in SnapCenter per VMware vSphere. 
---
= Aggiungere una singola VM o un datastore a un gruppo di risorse
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi aggiungere rapidamente una singola macchina virtuale o un datastore a qualsiasi gruppo di risorse esistente gestito dal plug-in SnapCenter per VMware vSphere.

.A proposito di questa attività
È possibile aggiungere datastore SAN e NAS ma non datastore VSAN o VVOL.

.Fasi
. Nell'interfaccia utente del client vSphere, seleziona *Menu* nella barra degli strumenti e vai alla VM o al datastore che desideri aggiungere.
. Nel riquadro di navigazione sinistro, fare clic con il pulsante destro del mouse sulla macchina virtuale o sul datastore, selezionare *Plug-in SnapCenter per VMware vSphere* > *Aggiungi al gruppo di risorse* dall'elenco a discesa secondario.
+
Il sistema verifica prima che SnapCenter gestisca e sia compatibile con il sistema di storage su cui si trova la macchina virtuale selezionata, quindi visualizza la pagina *Aggiungi a gruppo di risorse*. Se il messaggio `SnapCenter Compatibility Error` Quindi la macchina virtuale selezionata non è compatibile con SnapCenter ed è necessario prima aggiungere la macchina virtuale di storage appropriata a SnapCenter.

. Nella pagina *Aggiungi a gruppo di risorse*, selezionare un gruppo di risorse, quindi selezionare *OK*.
+
Quando si seleziona *OK*, il sistema controlla innanzitutto che SnapCenter gestisce ed è compatibile con lo storage in cui si trovano le macchine virtuali o gli archivi dati selezionati.

+
Se viene visualizzato il messaggio `Selected <resource-name> is not SnapCenter compatible` , una macchina virtuale o un archivio dati selezionati non è compatibile con SnapCenter. Per ulteriori informazioni, fare riferimento link:scpivs44_create_resource_groups_for_vms_and_datastores.html#manage-compatibility-check-failures["Gestire gli errori del controllo di compatibilità"] a.


