---
sidebar: sidebar 
permalink: scpivs44_add_storage_01.html 
keywords:  
summary: 'L"aggiunta di storage consente al plug-in SnapCenter per VMware vSphere di riconoscere e gestire le operazioni di backup e ripristino in vCenter.' 
---
= Aggiungere storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di eseguire il backup o il ripristino delle macchine virtuali, è necessario aggiungere cluster di storage o macchine virtuali di storage. L'aggiunta di storage consente al plug-in SnapCenter per VMware vSphere di riconoscere e gestire le operazioni di backup e ripristino in vCenter.

* Quale interfaccia utente utilizzare
+
Utilizzare il client VMware vSphere per aggiungere storage.

* LUN grandi
+
Il plug-in SnapCenter per VMware vSphere 4.5 e versioni successive supporta datastore su LUN di grandi dimensioni fino a 128 TB su aggregati ASA. Per LUN di grandi dimensioni, SnapCenter supporta solo LUN con thick provisioning per evitare la latenza.

* Volumi virtuali VMware (vVol)
+
È necessario aggiungere cluster di storage al plug-in SnapCenter per i tool VMware vSphere e ONTAP per VMware vSphere per vVol DataProtection per funzionare.

+
Per ulteriori informazioni, fare riferimento alla documentazione degli ONTAP tools for VMware vSphere . Inoltre, fare riferimento a https://imt.netapp.com/imt/imt.jsp?components=180121;&solution=1517&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] per informazioni aggiornate sulle versioni supportate dagli strumenti ONTAP .



.Prima di iniziare
Il server ESXi, il plug-in SnapCenter per VMware vSphere e ogni vCenter devono essere sincronizzati allo stesso tempo. Se si tenta di aggiungere spazio di archiviazione ma le impostazioni dell'ora per vCenter non sono sincronizzate, l'operazione potrebbe non riuscire e causare un errore nel certificato Java.

.A proposito di questa attività
Il plug-in di SnapCenter per VMware vSphere esegue operazioni di backup e ripristino su macchine virtuali storage connesse direttamente e su macchine virtuali storage in un cluster storage.


NOTE: Se si utilizza il SnapCenter Plug-in for VMware vSphere per supportare i backup basati sulle applicazioni sui VMDK, è necessario utilizzare l'interfaccia utente di SnapCenter per immettere i dettagli di autenticazione dell'archiviazione e registrare i sistemi di archiviazione.

* Per i vCenter in modalità Linked, è necessario aggiungere separatamente i sistemi storage a ciascun vCenter.
* Se si aggiunge SVM, i nomi delle VM di storage devono essere risolti nelle LIF di gestione.
+
Se sono state aggiunte voci al file _etc\hosts_ per i nomi delle VM di archiviazione in SnapCenter, è necessario assicurarsi che siano risolvibili anche dall'appliance virtuale. In caso contrario, è necessario aggiungere voci simili al file _etc/hosts_ all'interno del dispositivo.

+
Se si aggiunge una VM di storage con un nome che non è in grado di risolvere nella LIF di gestione, i processi di backup pianificati non vengono eseguiti perché il plug-in non è in grado di rilevare alcun datastore o volume nella VM di storage. In questo caso, aggiungere la VM di storage a SnapCenter e specificare la LIF di gestione oppure aggiungere un cluster contenente la VM di storage e specificare la LIF di gestione del cluster.

* I dettagli dell'autenticazione dello storage non vengono condivisi tra le istanze multiple del plug-in SnapCenter per VMware vSphere o tra Windows SnapCenter Server e il plug-in SnapCenter su vCenter.


.Fasi
. Dalla pagina di collegamento del client vCenter, selezionare Plug-in SnapCenter per VMware vSphere (SCV).
. Nel riquadro di navigazione sinistro di SCV, selezionare *Dashboard* > *Storage Systems*.
. Nella pagina Storage Systems (sistemi storage), selezionare l'opzione *Add* (Aggiungi).
. Nella procedura guidata *Add Storage System*, immettere le informazioni di base relative alla VM di storage o al cluster, come indicato nella seguente tabella:
+
|===
| Per questo campo… | Eseguire questa operazione… 


| Sistema storage | Inserisci l'indirizzo IP dell'FQDN o della LIF di gestione di un cluster storage o di una VM storage. Il plug-in SnapCenter per VMware vSphere non supporta più macchine virtuali storage con lo stesso nome in cluster diversi. 


| Metodo di autenticazione | Selezionare credenziali o certificato. Sono supportati due tipi di certificati: - https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_self-signed_certificate_for_storage_system_authentication_with_SCV["Certificato autofirmato"^] - https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_CA_signed_certificate_for_storage_system_authentication_with_SCV["Certificato FIRMATO CA"]. 


| Nome utente | Questo campo è visibile quando si seleziona credenziali come metodo di autenticazione. Inserire il nome utente ONTAP utilizzato per accedere alla VM di storage o al cluster. 


| Password | Questo campo è visibile quando si seleziona credenziali come metodo di autenticazione. Inserire la password di accesso alla VM di storage o al cluster. 


| Certificato | Questo campo è visibile quando si seleziona certificato come metodo di autenticazione. Selezionare il file del certificato. 


| Chiave privata | Questo campo è visibile quando si seleziona certificato come metodo di autenticazione. Selezionare il file della chiave privata. 


| Protocollo | Selezionare il protocollo di storage. 


| Porta | Porta accettata dal sistema di archiviazione.
- 443 per la connessione HTTPS
- 80 per la connessione HTTP 


| Timeout | Immettere il numero di secondi che il plug-in SnapCenter per VMware vSphere deve attendere prima di terminare l'operazione. Il valore predefinito è 60 secondi. 


| Indirizzo IP preferito | Se la macchina virtuale dello storage dispone di più indirizzi IP di gestione, selezionare questa casella e immettere l'indirizzo IP che si desidera utilizzare con il plug-in SnapCenter per VMware vSphere. *Nota:* non utilizzare parentesi quadre ([]) quando si inserisce l'indirizzo IP. 


| Sistema di gestione degli eventi (EMS) e impostazione AutoSupport | Se si desidera inviare messaggi EMS al syslog del sistema di storage o inviare messaggi AutoSupport al sistema di storage per la protezione applicata, le operazioni di ripristino completate o le operazioni non riuscite, selezionare la casella di controllo appropriata. Selezionare la casella di controllo *Invia notifica AutoSupport per operazioni non riuscite al sistema di storage* e la casella di controllo *Registra eventi server SnapCenter su syslog* per attivare le notifiche AutoSupport. 


| Registrare gli eventi del server SnapCenter in syslog | Selezionare la casella per registrare gli eventi del plug-in SnapCenter per VMware vSphere. 


| Invia notifica AutoSupport per operazione non riuscita al sistema di storage | Selezionare questa casella se si desidera che venga inviata una notifica AutoSupport per i processi di protezione dei dati non riusciti. È inoltre necessario attivare AutoSupport sulla VM di storage e configurare le impostazioni e-mail di AutoSupport. 
|===
. Selezionare *Aggiungi*.
+
Se è stato aggiunto un cluster di storage, tutte le VM di storage in tale cluster vengono aggiunte automaticamente. Le VM di storage aggiunte automaticamente (a volte chiamate VM di storage "implicite") vengono visualizzate nella pagina di riepilogo del cluster con un trattino (-) invece di un nome utente. I nomi utente vengono visualizzati solo per le entità di storage esplicite.


