---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: È possibile creare, modificare ed eliminare gruppi di risorse di backup ed eseguire operazioni di backup su gruppi di risorse. 
---
= Gestire i gruppi di risorse
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare, modificare ed eliminare gruppi di risorse di backup ed eseguire operazioni di backup su gruppi di risorse.


NOTE: I gruppi di risorse sono denominati processi di backup in Virtual Storage Console (VSC).



== Sospendere e riprendere le operazioni sui gruppi di risorse

Sospendi le operazioni pianificate su un gruppo di risorse.  Riattivarli quando necessario.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *gruppi di risorse*, selezionare un gruppo di risorse e selezionare *Sospendi* (oppure selezionare *Riprendi*).
. Nella casella di conferma, selezionare *OK* per confermare.


.Al termine
Nella pagina gruppi di risorse, lo stato del lavoro per la risorsa sospesa è `Under_Maintenance`. Potrebbe essere necessario scorrere a destra della tabella per visualizzare la colonna Stato lavoro.

Una volta ripristinati i backup, lo stato del processo diventa `Production`.



== Modificare i gruppi di risorse

È possibile rimuovere o aggiungere risorse in gruppi di risorse in vCenter, scollegare o allegare policy, modificare pianificazioni o modificare qualsiasi altra opzione di gruppo di risorse.

.A proposito di questa attività
Se si desidera modificare il nome di un gruppo di risorse, non utilizzare i seguenti caratteri speciali nei nomi di macchine virtuali, datastore, policy, backup o gruppi di risorse:

% E * N. @! / : * ? " < > - | ; ' e spazio. È consentito un carattere di sottolineatura (_).

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *gruppi di risorse*, quindi selezionare un gruppo di risorse e selezionare *Modifica*.
. Nell'elenco a sinistra della procedura guidata *Modifica gruppo di risorse*, selezionare la categoria che si desidera modificare e immettere le modifiche.
+
È possibile apportare modifiche a più categorie. In questa opzione è anche possibile modificare le risorse secondarie protette.

. Selezionare *Avanti* finché non viene visualizzata la pagina Riepilogo, quindi selezionare *fine*.




== Eliminare i gruppi di risorse

Eliminare un gruppo di risorse in vCenter se non è necessario proteggere le risorse.  Eliminare tutti i gruppi di risorse prima di rimuovere il SnapCenter Plug-in for VMware vSphere.

.A proposito di questa attività
Tutte le operazioni di eliminazione dei gruppi di risorse vengono eseguite come eliminazioni forzate.  Quando si elimina un gruppo di risorse, il sistema scollega tutti i criteri dal gruppo di risorse vCenter, rimuove il gruppo di risorse dal SnapCenter Plug-in for VMware vSphere ed elimina tutti i backup e gli snapshot del gruppo di risorse.


NOTE: In una relazione SnapVault , non è possibile eliminare l'ultimo snapshot, pertanto non è possibile eliminare il gruppo di risorse.  Prima di eliminare un gruppo di risorse in una relazione SnapVault , utilizzare System Manager o ONTAP CLI per rimuovere la relazione, quindi eliminare l'ultimo snapshot.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *gruppi di risorse*, quindi selezionare un gruppo di risorse e selezionare *Elimina*.
. Nella finestra di dialogo di conferma *Elimina gruppo di risorse*, seleziona *OK* per confermare.  L'eliminazione di un gruppo di risorse non rimuove la protezione secondaria.  Se necessario, utilizzare Gestione sistema per eliminare la protezione secondaria.  I gruppi di coerenza creati per il gruppo di risorse non vengono rimossi automaticamente; è necessario eliminarli manualmente da ONTAP utilizzando System Manager o un'altra interfaccia supportata.

