---
sidebar: sidebar 
permalink: scpivs44_upgrade_to_a_new_patch.html 
keywords:  
summary: 'Se si esegue l"aggiornamento a una nuova patch della stessa release, è necessario cancellare la cache del plug-in SnapCenter per VMware vSphere sul server Web vCenter e riavviare il server prima dell"aggiornamento o della registrazione.' 
---
= Eseguire l'aggiornamento a una nuova patch della stessa release del plug-in SnapCenter per VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si esegue l'aggiornamento a una nuova patch della stessa release, è necessario cancellare la cache del plug-in SnapCenter per VMware vSphere sul server Web vCenter e riavviare il server prima dell'aggiornamento o della registrazione.

Se la cache del plug-in non viene cancellata, i job recenti non vengono visualizzati nella dashboard e nel monitor dei job nei seguenti scenari:

* Il plug-in SnapCenter per VMware vSphere è stato implementato utilizzando vCenter e successivamente aggiornato a una patch nella stessa release.
* L'appliance virtuale VMware di SnapCenter è stata implementata in vCenter 1. In seguito, questo plug-in SnapCenter per VMware vSphere è stato registrato al nuovo vCenter2. Viene creata una nuova istanza del plug-in SnapCenter per VMware vSphere con una patch e registrata su vCenter1. Tuttavia, poiché vCenter1 ha ancora il plug-in memorizzato nella cache del primo plug-in SnapCenter per VMware vSphere senza la patch, è necessario cancellare la cache.




== Procedura per la cancellazione della cache

. Individuare il `vsphere-client-serenity` quindi individuare `com.netapp.scv.client-<release-number>` ed eliminarla.
+
Il nome della cartella cambia per ogni release.

+
Consultare la documentazione VMware per individuare la `vsphere-client-serenity` cartella del sistema operativo in uso.

. Riavviare vCenter Server.
+
A questo punto, è possibile aggiornare il plug-in di SnapCenter per VMware vSphere.


