---
sidebar: sidebar 
permalink: scpivs44_minimum_ontap_privileges_required.html 
keywords:  
summary: I privilegi minimi di ONTAP richiesti variano in base ai plug-in di SnapCenter utilizzati per la protezione dei dati. 
---
= Privilegi ONTAP richiesti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
I privilegi minimi di ONTAP richiesti variano in base ai plug-in di SnapCenter utilizzati per la protezione dei dati.


NOTE: A partire dal plug-in SnapCenter per VMware (SCV) 5,0, è necessario aggiungere applicazioni di tipo HTTP e ONTAPI come metodi di accesso utente per qualsiasi utente ONTAP con accesso personalizzato basato sui ruoli al SCV. Senza l'accesso a queste applicazioni, i backup non avranno esito positivo. È necessario riavviare il servizio SCV per riconoscere le modifiche apportate ai metodi di accesso utente ONTAP.



== Sono richiesti privilegi minimi per ONTAP

Tutti i plug-in di SnapCenter richiedono i seguenti privilegi minimi.

|===


| All-access comands (comandi all-access): Privilegi minimi richiesti per ONTAP 8.3 e versioni successive 


| visualizzazione dell'identità del cluster 


| event generate-autosupport-log 


| mostra la cronologia dei lavori
mostra lavoro
interruzione del lavoro 


| lun lun create lun delete lun igroup add lun igroup create lun igroup delete lun igroup rename lun igroup show lun mapping add-reporting-nodes lun mapping create lun mapping delete lun mapping remove-reporting-nodes lun mapping show lun modify lun move-in-volume lun offline lun online lun persistent-reservation clear lun resize serial lun lun show 


| elenco di destinazioni di snapmirror policy di snapmirror policy di aggiunta regola di snapmirror policy di modifica regola di snapmirror policy di rimozione regola di snapmirror policy di snapmirror di snapmirror di snapmirror show-history di snapmirror update-ls-set di snapmirror 


| Versione 


| creazione del clone del volume
visualizzazione del clone del volume
avvio della divisione del clone del volume
interruzione della divisione del clone del volume
creazione del volume
eliminazione dei volumi
distruggere il volume
creazione del clone del file di volume
file di volume show-disk-usage
volume offline
volume online
modifica del volume
creazione del qtree del volume
eliminazione del qtree del volume
modifica del qtree del volume
visualizzazione del qtree del volume
limitazione del volume
presentazione del volume
creazione di snapshot di volume
eliminazione dello snapshot del volume
modifica dello snapshot del volume
rinominare lo snapshot del volume
ripristino dello snapshot del volume
file di ripristino dello snapshot del volume
visualizzazione di snapshot di volume
smontare il volume 


| vserver cifs vserver cifs share create vserver cifs share delete vserver cifs shadowcopy show vserver cifs share show vserver cifs show vserver export-policy vserver export-policy create vserver export-policy delete vserver export-policy rule create vserver export-policy show vserver export-policy show vserver iscsi vserver show network interface visualizzazione dell'interfaccia di rete con gruppi di failover dell'interfaccia di rete 
|===
|===
| Comandi di sola lettura: Privilegi minimi richiesti per ONTAP 8.3 e versioni successive 


| peer vserver vserver 
|===

NOTE: È possibile ignorare i messaggi di avviso relativi ai comandi Vserver non supportati.



== Ulteriori informazioni su ONTAP

* Se si utilizza ONTAP 8.2.x:
+
Devi effettuare l'accesso come `vsadmin` Sulla VM di storage per disporre dei privilegi appropriati per il plug-in SnapCenter per le operazioni di VMware vSphere.

* Se si utilizza ONTAP 8.3 e versioni successive:
+
Devi effettuare l'accesso come `vsadmin` o con un ruolo che ha i privilegi minimi elencati nelle tabelle precedenti.

* Per creare e gestire i ruoli utente, è necessario essere l'amministratore del cluster. È possibile associare gli utenti a una macchina virtuale per lo storage in cluster o a una macchina virtuale per lo storage.
* È necessario ONTAP 9.12.1 o versioni successive per utilizzare la funzionalità SnapMirror Business Continuity (SM-BC).
* Per utilizzare la funzione di istantanea antimanomissione (TPS):
+
** È necessario ONTAP 9.13.1 e versioni successive per SAN
** Per NFS sono necessarie ONTAP 9.12.1 e versioni successive





NOTE: Per ONTAP versione 9.11.1 e versioni successive, la comunicazione con il cluster ONTAP avviene tramite le API REST. L'utente ONTAP deve avere l'applicazione http attivata. Tuttavia, se si riscontrano problemi con le API REST ONTAP, la chiave di configurazione "FORCE_ZAPI" consente il passaggio al flusso di lavoro ZAPI tradizionale. Potrebbe essere necessario aggiungere o aggiornare questa chiave utilizzando le API DI configurazione e impostarla su true. Vedere l'articolo della KB, https://kb.netapp.com/mgmt/SnapCenter/How_to_use_RestAPI_to_edit_configuration_parameters_in_SCV["Come utilizzare RestAPI per modificare i parametri di configurazione in SCV"].
