---
sidebar: sidebar 
permalink: scpivs44_how_to_configure_ontap_rbac_for_snapcenter_plug-in_for_vmware_vsphere.html 
keywords:  
summary: 'ONTAP RBAC si applica solo ai processi coerenti con le applicazioni (applicazione su VMDK) del server SnapCenter.' 
---
= Come configurare il plug-in ONTAP RBAC per SnapCenter per VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP RBAC si applica solo ai processi coerenti con le applicazioni (applicazione su VMDK) del server SnapCenter.


NOTE: A partire dal plug-in SnapCenter per VMware (SCV) 5,0, è necessario aggiungere applicazioni di tipo HTTP e ONTAPI come metodi di accesso utente per qualsiasi utente ONTAP con accesso personalizzato basato sui ruoli al SCV. Senza l'accesso a queste applicazioni, i backup non avranno esito positivo. È necessario riavviare il servizio SCV per riconoscere le modifiche apportate ai metodi di accesso utente ONTAP. Per informazioni sulla creazione o la modifica degli account di accesso, fare riferimento alla sezione https://docs.netapp.com/us-en/ontap/authentication/config-worksheets-reference.html["Fogli di lavoro per l'autenticazione dell'amministratore e la configurazione RBAC"].

Devi configurare RBAC ONTAP sul sistema storage se vuoi utilizzarlo con il plug-in SnapCenter per VMware vSphere. Da ONTAP, è necessario eseguire le seguenti operazioni:

* Creare un singolo ruolo.
+
https://docs.netapp.com/us-en/ontap/concepts/administrator-authentication-rbac-concept.html["Autenticazione amministratore e RBAC"]

* Creare un nome utente e una password (credenziali del sistema di storage) in ONTAP per il ruolo.
+
Questa credenziale del sistema di archiviazione è necessaria per consentire la configurazione dei sistemi di archiviazione per il plug-in SnapCenter per VMware vSphere. A tale scopo, immettere le credenziali nel plug-in. Ogni volta che si accede a un sistema storage utilizzando queste credenziali, viene visualizzato il set di funzioni di SnapCenter impostato in ONTAP al momento della creazione delle credenziali.



È possibile utilizzare l'accesso come amministratore o root per accedere a tutte le attività di SnapCenter; tuttavia, è consigliabile utilizzare la funzionalità RBAC fornita da ONTAP per creare uno o più account personalizzati con privilegi di accesso limitati.

Per ulteriori informazioni, fare riferimento a link:scpivs44_minimum_ontap_privileges_required.html["Sono richiesti privilegi minimi per ONTAP"^].
