---
sidebar: sidebar 
permalink: scpivs44_modify_storage_timeout.html 
keywords:  
summary: Anche se i backup sono stati eseguiti correttamente in passato, potrebbero iniziare a non funzionare quando il plug-in SnapCenter per VMware vSphere deve attendere che il sistema storage superi il periodo di timeout configurato. Se si verifica questa condizione, è possibile aumentare il timeout configurato. 
---
= Modificare il timeout dello storage configurato
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Anche se i backup sono stati eseguiti correttamente in passato, potrebbero iniziare a non funzionare quando il plug-in SnapCenter per VMware vSphere deve attendere che il sistema storage superi il periodo di timeout configurato. Se si verifica questa condizione, è possibile aumentare il timeout configurato.

L'errore potrebbe verificarsi `Unable to discover resources on SCV: Unable to get storage details for datastore <xxx>…`

.Fasi
. Nel client VMware vSphere, fare clic su *Storage Systems*.
. Nella pagina Storage Systems (sistemi storage), selezionare il sistema storage da modificare e fare clic su *Edit* (Modifica).
. Nel campo Timeout, aumentare il numero di secondi.
+

TIP: 180 secondi sono consigliati per ambienti di grandi dimensioni.


