---
sidebar: sidebar 
permalink: scpivs44_download_the_ova_open_virtual_appliance.html 
keywords:  
summary: Il file .tar include OVA, un insieme di microservizi per la protezione dei dati di macchine virtuali e datastore e il file di certificato. 
---
= Scarica Open Virtual Appliance (OVA)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di installare Open Virtual Appliance (OVA), aggiungere il certificato a vCenter. Il file .tar contiene i certificati OVA e Entrust Root e Intermediate; i certificati si trovano nella cartella dei certificati. L'implementazione di OVA è supportata in VMware vCenter 7u1 e versioni successive.

Nelle versioni di VMware vCenter 7.0.3 e successive, l'OVA firmato dal certificato Entrust non è più attendibile. Per risolvere il problema, attenersi alla seguente procedura.

.Fasi
. Per scaricare il plug-in SnapCenter per VMware:
+
** Accedere al NetApp Support Site ( https://mysupport.netapp.com/products/index.html["https://mysupport.netapp.com/products/index.html"^]).
** Dall'elenco dei prodotti, selezionare *Plug-in SnapCenter per VMware vSphere*, quindi selezionare il pulsante *Scarica ultima release*.
** Scarica il plug-in SnapCenter per VMware vSphere `.tar` file in qualsiasi posizione.


. Estrarre il contenuto del file tar. Il file tar contiene la cartella OVA e certs. La cartella certs contiene i certificati Entrust Root e Intermediate.
. Accedere con il client vSphere al server vCenter.
. Accedere a *Amministrazione > certificati > Gestione certificati*.
. Accanto a *certificati principali attendibili*, selezionare *Aggiungi*
+
** Accedere alla cartella _certs_.
** Selezionare i certificati Entrust Root e Intermediate.
** Installare ciascun certificato uno alla volta.


. I certificati vengono aggiunti a un pannello in *certificati root attendibili*. Una volta installati i certificati, è possibile verificare e implementare OVA.



NOTE: Se l'OVA scaricato non viene manomesso, nella colonna *Publisher* viene visualizzato *Trusted certificate*.
