---
sidebar: sidebar 
permalink: scpivs44_manage_policies.html 
keywords:  
summary: È possibile creare, modificare, visualizzare, scollegare ed eliminare i criteri di backup per il plug-in SnapCenter per VMware vSphere. Per eseguire le operazioni di protezione dei dati sono necessarie policy. 
---
= Gestire le policy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare, modificare, visualizzare, scollegare ed eliminare i criteri di backup per il plug-in SnapCenter per VMware vSphere. Per eseguire le operazioni di protezione dei dati sono necessarie policy.



== Scollegare le policy

È possibile scollegare le policy da un gruppo di risorse SnapCenter Plug-in per VMware vSphere se non si desidera più che tali policy regolino la protezione dei dati per le risorse. È necessario scollegare una policy prima di poterla rimuovere o prima di modificarla.

.A proposito di questa attività
Le linee guida per la rimozione dei criteri dai gruppi di risorse del plug-in SnapCenter per VMware vSphere differiscono dalle linee guida per i gruppi di risorse SnapCenter. Per un gruppo di risorse client VMware vSphere, è possibile scollegare tutte le policy, lasciando il gruppo di risorse privo di policy. Tuttavia, per eseguire operazioni di protezione dei dati su quel gruppo di risorse, è necessario allegare almeno un criterio.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *gruppi di risorse*, quindi selezionare un gruppo di risorse e selezionare *Modifica*.
. Nella pagina *Criteri* della procedura guidata *Modifica gruppo di risorse*, deselezionare il segno di spunta accanto ai criteri che si desidera scollegare.
+
È inoltre possibile aggiungere un criterio al gruppo di risorse controllando il criterio.

. Apportare eventuali modifiche aggiuntive al gruppo di risorse nel resto della procedura guidata, quindi selezionare *fine*.




== Modificare i criteri

È possibile modificare i criteri per un plug-in SnapCenter per il gruppo di risorse VMware vSphere. È possibile modificare la frequenza, le opzioni di replica, le impostazioni di conservazione degli snapshot o le informazioni sugli script quando un criterio è collegato a un gruppo di risorse.

.A proposito di questa attività
La modifica del plug-in SnapCenter per backup VMware vSphere è diversa da quella delle policy di backup per i plug-in SnapCenter basati sulle applicazioni. Non è necessario scollegare i criteri dai gruppi di risorse quando si modificano i criteri del plug-in.

Prima di modificare le impostazioni di replica o conservazione, è necessario prendere in considerazione le possibili conseguenze.

* Aumento delle impostazioni di replica o conservazione
+
I backup continuano ad accumularsi finché non raggiungono la nuova impostazione.

* Riduzione delle impostazioni di replica o conservazione
+
I backup in eccesso rispetto alla nuova impostazione vengono cancellati quando viene eseguito il backup successivo.




NOTE: Per modificare la pianificazione di un plug-in SnapCenter per VMware vSphere, è necessario modificare la pianificazione nel gruppo di risorse del plug-in.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *Policies*, quindi selezionare un criterio e selezionare *Edit*.
. Modificare i campi dei criteri.
. Al termine, selezionare *Aggiorna*.


Le modifiche hanno effetto quando viene eseguito il successivo backup pianificato.



== Eliminare i criteri

Se non si richiede più una policy di backup configurata per il plug-in SnapCenter per VMware vSphere, potrebbe essere necessario eliminarla.

.Prima di iniziare
È necessario scollegare il criterio da tutti i gruppi di risorse nell'appliance virtuale per SnapCenter prima di poterlo eliminare.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *Policies*, quindi selezionare una policy e selezionare *Remove*.
. Nella finestra di dialogo di conferma, selezionare *OK*.

