---
sidebar: sidebar 
permalink: scpivs44_manage_resource_groups.html 
keywords:  
summary: È possibile creare, modificare ed eliminare gruppi di risorse di backup ed eseguire operazioni di backup su gruppi di risorse. 
---
= Gestire i gruppi di risorse
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare, modificare ed eliminare gruppi di risorse di backup ed eseguire operazioni di backup su gruppi di risorse.


NOTE: I gruppi di risorse sono denominati processi di backup in Virtual Storage Console (VSC).



== Sospendere e riprendere le operazioni sui gruppi di risorse

È possibile disattivare temporaneamente l'avvio delle operazioni pianificate su un gruppo di risorse. In un secondo momento, è possibile attivare tali operazioni.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *gruppi di risorse*, selezionare un gruppo di risorse e selezionare *Sospendi* (oppure selezionare *Riprendi*).
. Nella casella di conferma, selezionare *OK* per confermare.


.Al termine
Nella pagina gruppi di risorse, lo stato del lavoro per la risorsa sospesa è `Under_Maintenance`. Potrebbe essere necessario scorrere a destra della tabella per visualizzare la colonna Stato lavoro.

Una volta ripristinati i backup, lo stato del processo diventa `Production`.



== Modificare i gruppi di risorse

È possibile rimuovere o aggiungere risorse in gruppi di risorse in vCenter, scollegare o allegare policy, modificare pianificazioni o modificare qualsiasi altra opzione di gruppo di risorse.

.A proposito di questa attività
Se si desidera modificare il nome di un gruppo di risorse, non utilizzare i seguenti caratteri speciali nei nomi di macchine virtuali, datastore, policy, backup o gruppi di risorse:

% E * N. @! / : * ? " < > - | ; ' , .

È consentito un carattere di sottolineatura (_).

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *gruppi di risorse*, quindi selezionare un gruppo di risorse e selezionare *Modifica*.
. Nell'elenco a sinistra della procedura guidata *Modifica gruppo di risorse*, selezionare la categoria che si desidera modificare e immettere le modifiche.
+
È possibile apportare modifiche a più categorie. In questa opzione è anche possibile modificare le risorse secondarie protette.

. Selezionare *Avanti* finché non viene visualizzata la pagina Riepilogo, quindi selezionare *fine*.




== Eliminare i gruppi di risorse

È possibile eliminare un gruppo di risorse in vCenter se non è più necessario proteggere le risorse del gruppo di risorse. Prima di rimuovere il plug-in SnapCenter per VMware vSphere da vCenter, è necessario assicurarsi che tutti i gruppi di risorse siano stati eliminati.

.A proposito di questa attività
Tutte le operazioni di eliminazione dei gruppi di risorse vengono eseguite come eliminazione forzata. L'operazione di eliminazione scollega tutte le policy dal gruppo di risorse vCenter, rimuove il gruppo di risorse dal plug-in SnapCenter per VMware vSphere ed elimina tutti i backup e gli snapshot del gruppo di risorse.


NOTE: In una relazione SnapVault, non è possibile eliminare l'ultimo snapshot, pertanto non è possibile eliminare il gruppo di risorse. Prima di eliminare un gruppo di risorse che fa parte di una relazione SnapVault, è necessario utilizzare Gestione di sistema o l'interfaccia a riga di comando di ONTAP per rimuovere la relazione SnapVault, quindi è necessario eliminare l'ultimo snapshot.

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, selezionare *gruppi di risorse*, quindi selezionare un gruppo di risorse e selezionare *Elimina*.
. Nella casella di conferma *Elimina gruppo di risorse*, selezionare *OK* per confermare.

