---
sidebar: sidebar 
permalink: scpivs44_information_not_displayed_after_upgrading_to_a_new_patch_of_the_same_release.html 
keywords:  
summary: Dopo aver aggiornato il plug-in SnapCenter per VMware vSphere a una nuova patch della stessa release, i job recenti o altre informazioni potrebbero non essere visualizzati nella dashboard e nel monitor dei processi. 
---
= Informazioni non visualizzate dopo l'aggiornamento a una nuova patch della stessa release
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver aggiornato il plug-in SnapCenter per VMware vSphere a una nuova patch della stessa release, i job recenti o altre informazioni potrebbero non essere visualizzati nella dashboard e nel monitor dei processi.

Se si esegue l'aggiornamento a una nuova patch della stessa release, è necessario cancellare la cache del plug-in SnapCenter per VMware vSphere sul server Web vCenter e riavviare il server prima dell'aggiornamento o della registrazione.

Se la cache del plug-in non viene cancellata, i job recenti non vengono visualizzati nella dashboard e nel monitor dei job nei seguenti scenari:

* Il plug-in SnapCenter per VMware vSphere è stato implementato utilizzando vCenter e successivamente aggiornato a una patch nella stessa release.
* L'appliance virtuale VMware di SnapCenter è stata implementata in vCenter 1. In seguito, questo plug-in VMware di SnapCenter è stato registrato su un nuovo vCenter2. Una nuova istanza del plug-in VMware di SnapCenter viene creata con una patch e registrata in vCenter1. Tuttavia, poiché vCenter1 dispone ancora del plug-in memorizzato nella cache dal primo plug-in VMware di SnapCenter senza la patch, la cache deve essere cancellata.


La cache si trova nelle seguenti posizioni, in base al tipo di sistema operativo del server:

* Appliance vCenter Server Linux
+
`/etc/vmware/vsphere-client/vc-packages/vsphere-client-serenity/`

* Sistema operativo Windows
+
`%PROGRAMFILES%/VMware/vSphere client/vc-packages/vsphere-client-serenity/`





== Soluzione alternativa se è già stato eseguito l'aggiornamento prima di svuotare la cache

. Accedere alla GUI di gestione del plug-in VMware di SnapCenter.
+
L'IP viene visualizzato quando si implementa il plug-in VMware di SnapCenter.

. Fare clic su *Configuration* nel riquadro di navigazione a sinistra, quindi fare clic sull'opzione Service (Servizio) nella sezione *Plug-in Details* (Dettagli plug-in) per disattivare il plug-in.
+
Il servizio plug-in VMware di SnapCenter è disattivato e l'estensione non è registrata in vCenter.

. Individuare il `vsphere-client-serenity` quindi individuare `com.netapp.scv.client-<release-number>` ed eliminarla.
+
Il nome della cartella cambia per ogni release.

. Riavviare vCenter Server.
. Accedere al client VMware vSphere.
. Fare clic su *Configuration* nel riquadro di navigazione a sinistra, quindi fare clic sull'opzione Service (Servizio) nella sezione *Plug-in Details* (Dettagli plug-in) per attivare il plug-in.
+
Il servizio plug-in VMware di SnapCenter è attivato e l'estensione è registrata in vCenter.


