---
sidebar: sidebar 
permalink: scpivs44_restore_a_specific_backup_of_the_mysql_database.html 
keywords:  
summary: 'È possibile utilizzare la console di manutenzione per ripristinare un backup specifico del database MySQL (chiamato anche database NSM) per il plug-in SnapCenter per l"appliance virtuale VMware vSphere.' 
---
= Ripristinare un backup specifico del database MySQL
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare la console di manutenzione per ripristinare un backup specifico del database MySQL (chiamato anche database NSM) per il plug-in SnapCenter per l'appliance virtuale VMware vSphere.

.Fasi
. Aprire una finestra della console di manutenzione.
+
link:scpivs44_access_the_maintenance_console.html["Accedere alla console di manutenzione"^].

. Dal menu principale, immettere l'opzione *1) Application Configuration* (Configurazione applicazione).
. Dal menu Application Configuration (Configurazione applicazione), inserire l'opzione *6) MySQL backup and restore*.
. Dal menu di configurazione di MySQL Backup and Restore, immettere l'opzione *2) Elenca i backup MySQL*, quindi annotare il backup che si desidera ripristinare.
. Dal menu MySQL Backup and Restore Configuration (Configurazione backup e ripristino MySQL), inserire l'opzione *4) Restore MySQL backup* (Ripristina backup MySQL).
. Al prompt "Restore using the most recentent backup" (Ripristina utilizzando il backup più recente), immettere *n*.
. Quando viene visualizzato il messaggio "Backup to restore from" (Backup da ripristinare), immettere il nome del backup, quindi premere *Invio*.
+
Il database MySQL di backup selezionato viene ripristinato nella posizione originale.


