---
sidebar: sidebar 
permalink: scpivs44_modify_storage_timeout.html 
keywords:  
summary: Anche se in passato i backup sono stati eseguiti correttamente, potrebbero verificarsi degli errori durante il periodo in cui il plug-in di SnapCenter per VMware vSphere deve attendere che il sistema storage superi il periodo di timeout configurato. Se si verifica questa condizione, è possibile aumentare il timeout configurato. 
---
= Modificare il timeout dello storage configurato
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Anche se in passato i backup sono stati eseguiti correttamente, potrebbero verificarsi degli errori durante il periodo in cui il plug-in di SnapCenter per VMware vSphere deve attendere che il sistema storage superi il periodo di timeout configurato. Se si verifica questa condizione, è possibile aumentare il timeout configurato.

L'errore potrebbe verificarsi `Unable to discover resources on SCV: Unable to get storage details for datastore <xxx>…`

.Fasi
. Nel riquadro di navigazione sinistro del plug-in SCV, fare clic su *sistemi di memorizzazione*.
. Nella pagina Storage Systems (sistemi storage), selezionare il sistema storage da modificare e fare clic su *Edit* (Modifica).
. Nel campo Timeout, aumentare il numero di secondi.
+

TIP: 180 secondi sono consigliati per ambienti di grandi dimensioni.


