---
sidebar: sidebar 
permalink: scpivs44_upgrade_to_a_new_patch.html 
keywords:  
summary: 'Se si esegue l"aggiornamento a una nuova patch della stessa release, è necessario cancellare la cache del plug-in SnapCenter per VMware vSphere sul server Web vCenter e riavviare il server prima dell"aggiornamento o della registrazione.' 
---
= Eseguire l'aggiornamento a una nuova patch della stessa release del plug-in SnapCenter per VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si esegue l'aggiornamento a una nuova patch della stessa release, è necessario cancellare la cache del plug-in SnapCenter per VMware vSphere sul server Web vCenter e riavviare il server prima dell'aggiornamento o della registrazione.

Se la cache del plug-in non viene cancellata, i job recenti non vengono visualizzati nella dashboard e nel monitor dei job nei seguenti scenari:

* Il plug-in SnapCenter per VMware vSphere è stato implementato utilizzando vCenter e successivamente aggiornato a una patch nella stessa release.
* L'appliance virtuale VMware di SnapCenter è stata implementata in vCenter 1. In seguito, questo plug-in VMware di SnapCenter è stato registrato su un nuovo vCenter2. Una nuova istanza del plug-in VMware di SnapCenter viene creata con una patch e registrata in vCenter1. Tuttavia, poiché vCenter1 dispone ancora del plug-in memorizzato nella cache dal primo plug-in VMware di SnapCenter senza la patch, la cache deve essere cancellata.




== Procedura per la cancellazione della cache

. Individuare il `vsphere-client-serenity` quindi individuare `com.netapp.scv.client-<release-number>` ed eliminarla.
+
Il nome della cartella cambia per ogni release.

+
Consultare la documentazione VMware per individuare il percorso di `vsphere-client-serenity` per il sistema operativo in uso.

. Riavviare vCenter Server.
+
È quindi possibile aggiornare il plug-in VMware di SnapCenter.


