---
sidebar: sidebar 
permalink: scpivs44_add_storage_01.html 
keywords:  
summary: 'L"aggiunta di storage consente al plug-in SnapCenter per VMware vSphere di riconoscere e gestire le operazioni di backup e ripristino in vCenter.' 
---
= Aggiungere storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di eseguire il backup o il ripristino delle macchine virtuali, è necessario aggiungere cluster di storage o macchine virtuali di storage. L'aggiunta di storage consente al plug-in SnapCenter per VMware vSphere di riconoscere e gestire le operazioni di backup e ripristino in vCenter.

* Quale GUI utilizzare
+
Utilizzare il client VMware vSphere per aggiungere storage.

* LUN grandi
+
Il plug-in SnapCenter per VMware vSphere 4.5 e versioni successive supporta datastore su LUN di grandi dimensioni fino a 128 TB su aggregati ASA. Per LUN di grandi dimensioni, SnapCenter supporta solo LUN con thick provisioning per evitare la latenza.

* Volumi virtuali VMware (vVol)
+
È necessario aggiungere cluster di storage al plug-in SnapCenter per i tool VMware vSphere e ONTAP per VMware vSphere per vVol DataProtection per funzionare.

+
Per ulteriori informazioni, vedere https://docs.netapp.com/vapp-98/index.jsp["Strumenti ONTAP per VMware vSphere"^]



.Prima di iniziare
Il server ESXi, il plug-in VMware SnapCenter e ogni vCenter devono essere sincronizzati allo stesso tempo. Se si tenta di aggiungere spazio di archiviazione ma le impostazioni dell'ora per vCenter non sono sincronizzate, l'operazione potrebbe non riuscire e causare un errore nel certificato Java.

.A proposito di questa attività
Il plug-in VMware di SnapCenter esegue operazioni di backup e ripristino su macchine virtuali di storage collegate direttamente e su macchine virtuali di storage in un cluster di storage.


NOTE: Se si utilizza il plug-in VMware di SnapCenter per supportare backup basati su applicazioni su VMDK, è necessario utilizzare l'interfaccia grafica di SnapCenter per immettere i dettagli di autenticazione dello storage e registrare i sistemi storage.

* Per i vCenter in modalità Linked, è necessario aggiungere separatamente i sistemi storage a ciascun vCenter.
* Se si aggiunge SVM, i nomi delle VM di storage devono essere risolti nelle LIF di gestione.
+
Se sono state aggiunte voci al file _etc\hosts_ per i nomi delle VM di archiviazione in SnapCenter, è necessario assicurarsi che siano risolvibili anche dall'appliance virtuale. In caso contrario, è necessario aggiungere voci simili al file _etc/hosts_ all'interno del dispositivo.

+
Se si aggiunge una VM di storage con un nome che non è in grado di risolvere nella LIF di gestione, i processi di backup pianificati non vengono eseguiti perché il plug-in non è in grado di rilevare alcun datastore o volume nella VM di storage. In questo caso, aggiungere la VM di storage a SnapCenter e specificare la LIF di gestione oppure aggiungere un cluster contenente la VM di storage e specificare la LIF di gestione del cluster.

* I dettagli relativi all'autenticazione dello storage non vengono condivisi tra più istanze del plug-in VMware di SnapCenter o tra il server SnapCenter di Windows e il plug-in SnapCenter su vCenter.


.Fasi
. Nel riquadro sinistro di Navigator del client vSphere, fare clic su *Storage Systems*.
. Nella pagina Storage Systems (sistemi storage), selezionare l'opzione *Add* (Aggiungi).
. Nella procedura guidata *Add Storage System*, immettere le informazioni di base relative alla VM di storage o al cluster, come indicato nella seguente tabella:
+
|===
| Per questo campo… | Eseguire questa operazione… 


| Sistema storage | Inserisci l'indirizzo IP dell'FQDN o della LIF di gestione di un cluster storage o di una VM storage.
Il plug-in VMware di SnapCenter non supporta più VM storage con lo stesso nome su cluster diversi. 


| Metodo di autenticazione | Selezionare credenziali o certificato. Sono supportati due tipi di certificati: - https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_CA_signed_certificate_for_storage_system_authentication_with_SCV["Certificato FIRMATO CA"^]- https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_configure_a_self-signed_certificate_for_storage_system_authentication_with_SCV["Certificato autofirmato"^] 


| Nome utente | Questo campo è visibile quando si seleziona credenziali come metodo di autenticazione. Inserire il nome utente ONTAP utilizzato per accedere alla VM di storage o al cluster. 


| Password | Questo campo è visibile quando si seleziona credenziali come metodo di autenticazione. Inserire la password di accesso alla VM di storage o al cluster. 


| Certificato | Questo campo è visibile quando si seleziona certificato come metodo di autenticazione. Selezionare il file del certificato. 


| Chiave privata | Questo campo è visibile quando si seleziona certificato come metodo di autenticazione. Selezionare il file della chiave privata. 


| Protocollo | Selezionare il protocollo di storage. 


| Porta | Porta accettata dal sistema di archiviazione.
- 443 per la connessione HTTPS
- 80 per la connessione HTTP 


| Timeout | Immettere il numero di secondi che il plug-in SnapCenter VMware deve attendere prima di terminare l'operazione. L'impostazione predefinita è 60 secondi. 


| IP preferito | Se la VM di storage dispone di più indirizzi IP di gestione, selezionare questa casella e immettere l'indirizzo IP che si desidera utilizzare con il plug-in SnapCenter VMware.
*Nota:* non utilizzare parentesi quadre ([]) quando si inserisce l'indirizzo IP. 


| Sistema di gestione degli eventi (EMS) e impostazione AutoSupport | Se si desidera inviare messaggi EMS al syslog del sistema di storage o inviare messaggi AutoSupport al sistema di storage per la protezione applicata, le operazioni di ripristino completate o le operazioni non riuscite, selezionare la casella di controllo appropriata. Selezionare la casella di controllo *Invia notifica AutoSupport per operazioni non riuscite al sistema di storage* e la casella di controllo *Registra eventi server SnapCenter su syslog* per attivare le notifiche AutoSupport. 


| Registrare gli eventi del server SnapCenter in syslog | Selezionare la casella per registrare gli eventi per il plug-in VMware di SnapCenter. 


| Invia notifica AutoSupport per operazione non riuscita al sistema di storage | Selezionare questa casella se si desidera che venga inviata una notifica AutoSupport per i processi di protezione dei dati non riusciti. È inoltre necessario attivare AutoSupport sulla VM di storage e configurare le impostazioni e-mail di AutoSupport. 
|===
. Fare clic su *Aggiungi*.
+
Se è stato aggiunto un cluster di storage, tutte le VM di storage in tale cluster vengono aggiunte automaticamente. Le VM di storage aggiunte automaticamente (a volte chiamate VM di storage "implicite") vengono visualizzate nella pagina di riepilogo del cluster con un trattino (-) invece di un nome utente. I nomi utente vengono visualizzati solo per le entità di storage esplicite.


