---
sidebar: sidebar 
permalink: scpivs44_rest_apis_fail_stuck_jobs.html 
keywords:  
summary: Per trovare gli ID lavoro per i lavori del client VMware vSphere utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario utilizzare le chiamate API REST per VMware vSphere. 
---
= API REST per contrassegnare i lavori bloccati come non riusciti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Per trovare gli ID lavoro per i lavori del client VMware vSphere utilizzando il plug-in SnapCenter per le API REST di VMware vSphere, è necessario utilizzare le chiamate API REST per VMware vSphere. Queste API REST sono state aggiunte nel plug-in SnapCenter per VMware vSphere 4.4.

Per ogni API REST, aggiungere \https://<server>:<port>` nella parte anteriore dell'API REST per formare un endpoint completo.

Utilizzare la seguente API REST nella sezione lavori per modificare i lavori bloccati in uno stato di esecuzione in uno stato di errore:

|===
| API REST | Commenti 


| `/4.1/jobs/{id}/failJobs` | Quando si passano gli ID dei lavori bloccati in uno stato di esecuzione, `failJobs` contrassegna tali lavori come non riusciti. Per identificare i lavori bloccati in uno stato di esecuzione, utilizzare la GUI di monitoraggio dei lavori per visualizzare lo stato di ogni lavoro e l'ID del lavoro. 
|===