---
sidebar: sidebar 
permalink: scpivs44_detach_a_virtual_disk.html 
keywords:  
summary: Dopo aver collegato un disco virtuale per ripristinare i singoli file, è possibile scollegare il disco virtuale dalla macchina virtuale padre. 
---
= Scollegare un disco virtuale
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Dopo aver collegato un disco virtuale per ripristinare i singoli file, è possibile scollegare il disco virtuale dalla macchina virtuale padre.

.Fasi
. Nell'interfaccia utente del client VMware vSphere, selezionare *Menu* nella barra degli strumenti, quindi selezionare *VM e modelli* dall'elenco a discesa.
. Nel riquadro di sinistra del navigatore, selezionare una VM.
. Nel riquadro di spostamento di sinistra, fare clic con il pulsante destro del mouse sulla macchina virtuale, quindi selezionare *Plug-in SnapCenter per VMware vSphere* nell'elenco a discesa, quindi selezionare *Disconnetti disco virtuale* nell'elenco a discesa secondario.
. Nella schermata *Disconnetti disco virtuale*, selezionare uno o più dischi da scollegare, quindi selezionare la casella di controllo *Scollega i dischi selezionati* e selezionare *Scollega*.
+

IMPORTANT: Assicurarsi di selezionare il disco virtuale corretto. La selezione del disco errato potrebbe influire sul lavoro di produzione.

. Facoltativo: Monitorare l'avanzamento dell'operazione nella sezione *attività recenti*.
+
Aggiornare la schermata per visualizzare le informazioni aggiornate.

. Verificare che il disco virtuale sia scollegato eseguendo le seguenti operazioni:
+
.. Selezionare *Menu* nella barra degli strumenti, quindi selezionare *VM e modelli* dall'elenco a discesa.
.. Nel riquadro di sinistra del navigatore, fare clic con il pulsante destro del mouse su una macchina virtuale, quindi selezionare *Modifica impostazioni* nell'elenco a discesa.
.. Nella finestra *Edit Settings* (Modifica impostazioni), espandere l'elenco di ciascun disco rigido per visualizzare l'elenco dei file su disco.
+
La pagina *Edit Settings* (Modifica impostazioni) elenca i dischi sulla macchina virtuale. È possibile espandere i dettagli di ciascun disco rigido per visualizzare l'elenco dei dischi virtuali collegati.




