---
sidebar: sidebar 
permalink: scpivs44_unregister_plugin_from_vcenter.html 
keywords:  
summary: Se si interrompe il servizio plug-in SnapCenter per VMware vSphere in un vCenter in modalità collegata, i gruppi di risorse non sono disponibili in tutti i vCenter collegati, anche quando il servizio plug-in SnapCenter per VMware vSphere è in esecuzione negli altri vCenter collegati. È necessario annullare la registrazione manuale del plug-in SnapCenter per le estensioni di VMware vSphere. 
---
= Annullare la registrazione del plug-in SnapCenter per VMware vSphere da vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se si interrompe il servizio plug-in SnapCenter per VMware vSphere in un vCenter in modalità collegata, i gruppi di risorse non sono disponibili in tutti i vCenter collegati, anche quando il servizio plug-in SnapCenter per VMware vSphere è in esecuzione negli altri vCenter collegati.

È necessario annullare la registrazione manuale del plug-in SnapCenter per le estensioni di VMware vSphere.

.Fasi
. Sul vCenter collegato che ha arrestato il servizio SnapCenter Plug-in per VMware vSphere, accedere al gestore MOB (Managed Object Reference).
. Nell'opzione Proprietà, selezionare *content* nella colonna valore, quindi nella schermata successiva selezionare *ExtensionManager* nella colonna valore per visualizzare un elenco degli interni registrati.
. Annullare la registrazione delle estensioni `com.netapp.scv.client` e. `com.netapp.aegis`.

