---
sidebar: sidebar 
permalink: scv48_add_certificates_to_certificate_store.html 
keywords:  
summary: Aggiungere i certificati Root e Intermediate di Certificate Authority a VMware vCenter per considerare attendibili il certificato e gli elementi firmati con esso. 
---
= Aggiungere certificati all'archivio certificati VMware
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Prima di installare Open Virtual Appliance (OVA), aggiungere il certificato a vCenter. Il file .tar contiene i certificati OVA e Entrust Root e Intermediate; i certificati si trovano nella cartella dei certificati. L'implementazione di OVA è supportata in VMware vCenter 7u1 e versioni successive.

Nelle versioni di VMware vCenter 7.0.3 e successive, l'OVA firmato dal certificato Entrust non è più attendibile. Per risolvere il problema, attenersi alla seguente procedura.

.Fasi
. Accedere con il client vSphere al server vCenter.
. Accedere a *Amministrazione > certificati > Gestione certificati*.
. Accanto a *Trusted Root Store*, fare clic su *Add* (Aggiungi)
. Cercare e selezionare la posizione dei certificati Entrust Root e Intermediate. Il certificato viene aggiunto in un pannello in *certificati root attendibili*. Una volta installati i certificati, è possibile verificare e implementare OVA.



NOTE: Se l'OVA scaricato non viene manomesso, nella colonna *Publisher* viene visualizzato *Trusted certificate*.
