---
sidebar: sidebar 
permalink: scv48_audit_logs.html 
keywords:  
summary: 'Il registro di audit fornisce la tracciabilità di chi ha fatto cosa e quando. Un registro di controllo è una raccolta di eventi in ordine cronologico che viene scritta in un file all"interno del dispositivo.' 
---
= Registri di audit
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un registro di controllo è una raccolta di eventi in ordine cronologico, che viene scritta in un file all'interno del dispositivo. I file di log di controllo vengono generati in `/var/log/netapp/audit` una posizione e i nomi dei file seguono una delle seguenti convenzioni di denominazione:

* Audit.log: File di log di audit attivo in uso.
* Audit-%d{yyyy-MM-dd-HH-mm-ss}.log.gz: Eseguito il rollover del file di log di audit. La data e l'ora nel nome del file indicano quando è stato creato il file, ad esempio: Audit-2022-12-15-16-28-01.log.gz.


Nell'interfaccia utente del plug-in SCV, è possibile visualizzare ed esportare i dettagli del registro di controllo da *Dashboard* > *Settings* > *Audit Logs* Tab. È possibile visualizzare l'audit delle operazioni nei registri di controllo. I registri di controllo vengono scaricati con il pacchetto di supporto.

Se sono configurate le impostazioni e-mail, SCV invia una notifica e-mail in caso di errore nella verifica dell'integrità del registro di controllo. Un errore di verifica dell'integrità del registro di controllo può verificarsi quando uno dei file viene manomesso o eliminato.

Le configurazioni predefinite dei file di audit sono:

* Il file di log di audit in uso può aumentare fino a un massimo di 10 MB
* Vengono conservati un massimo di 10 file di log di audit


I log di controllo di cui è stato eseguito il rollover vengono periodicamente verificati per verificarne l'integrità. SCV fornisce API REST per visualizzare i registri e verificarne l'integrità. Una pianificazione integrata attiva e assegna uno dei seguenti stati di integrità.

|===


| Stato | Descrizione 


| MANOMESSO | Il contenuto del file di log di audit viene modificato 


| NORMALE | Il file di log di audit non è stato modificato 


| SPOSTA IL MOUSE SU ELIMINA | - Il file di registro di controllo viene cancellato in base alla conservazione
Per impostazione predefinita, vengono conservati solo 10 file 


| ELIMINAZIONE IMPREVISTA | Il file di log di audit viene cancellato 


| ATTIVO | - Il file di log di audit è in uso
- Applicabile solo a audit.log 
|===
Gli eventi sono suddivisi in tre categorie principali:

* Eventi di protezione dei dati
* Eventi della console di manutenzione
* Eventi della console di amministrazione




== Eventi di protezione dei dati

Le risorse di SCV sono:

* Sistema storage
* Gruppo di risorse
* Policy
* Backup
* Iscrizione
* Account


La seguente tabella elenca le operazioni che possono essere eseguite su ciascuna risorsa:

|===


| *Risorse* | *Operazioni* 


| Sistema storage | Creato, modificato, eliminato 


| Iscrizione | Creato, modificato, eliminato 


| Account | Creato, modificato, eliminato 


| Gruppo di risorse | Creato, modificato, cancellato, sospeso, ripreso 


| Policy | Creato, modificato, eliminato 


| Backup | Creato, rinominato, cancellato, montato, non montato, Ripristino VMDK, ripristino VM, collegamento VMDK, scollegamento VMDK, Ripristino file guest 
|===


== Eventi della console di manutenzione

Le operazioni amministrative nella console di manutenzione vengono controllate. Le opzioni della console di manutenzione disponibili sono:

. Avvio/interruzione dei servizi
. Modificare nome utente e password
. Cambiare la password MySQL
. Configurare MySQL Backup
. Ripristinare MySQL Backup
. Modificare la password utente "maint"
. Modificare il fuso orario
. Modificare il server NTP
. Disattiva l'accesso SSH
. Aumentare le dimensioni del disco jail
. Eseguire l'upgrade
. Installare VMware Tools (stiamo lavorando per sostituire questo con strumenti Open-vm)
. Modificare le impostazioni dell'indirizzo IP
. Modificare le impostazioni di ricerca dei nomi di dominio
. Modificare i percorsi statici
. Accedere alla shell di diagnostica
. Abilitare l'accesso remoto alla diagnostica




== Eventi della console di amministrazione

Vengono controllate le seguenti operazioni nell'interfaccia utente della Admin Console:

* Impostazioni
+
** Modificare le credenziali di amministratore
** Modificare il fuso orario
** Modificare il server NTP
** Modificare le impostazioni degli indirizzi IPv4/IPv6


* Configurazione
+
** Modificare le credenziali vCenter
** Plug-in Enable/Disable (attiva/Disattiva plug-in






== Configurare i server syslog

I registri di audit vengono memorizzati all'interno dell'appliance e verificati periodicamente per verificarne l'integrità. L'inoltro degli eventi consente di ottenere eventi dal computer di origine o di inoltro e di memorizzarli in un computer centralizzato, ovvero Syslog Server. I dati vengono crittografati durante il trasferimento tra l'origine e la destinazione.

.Prima di iniziare
È necessario disporre dei privilegi di amministratore.

.A proposito di questa attività
Questa attività consente di configurare il server syslog.

.Fasi
. Accedere al plug-in SnapCenter per VMware vSphere.
. Nel riquadro di navigazione a sinistra, selezionare *Impostazioni* > *registri di controllo* > *Impostazioni*.
. Nel riquadro *Audit Log Settings*, selezionare *Send audit logs to Syslog server* (Invia log di controllo al server Syslog)
. Inserire i seguenti dati:
+
** IP server syslog
** Porta server syslog
** Formato RFC
** Certificato server syslog


. Fare clic su *SAVE* (SALVA) per salvare le impostazioni del server Syslog.




== Modificare le impostazioni del registro di controllo

È possibile modificare le configurazioni predefinite delle impostazioni del registro.

.Prima di iniziare
È necessario disporre dei privilegi di amministratore.

.A proposito di questa attività
Questa attività consente di modificare le impostazioni predefinite del registro di controllo.

.Fasi
. Accedere al plug-in SnapCenter per VMware vSphere.
. Nel riquadro di navigazione a sinistra, selezionare *Impostazioni* > *registri di controllo* > *Impostazioni*.
. Nel riquadro *Impostazioni registro di controllo*, immettere il numero massimo di file di registro di controllo e il limite di dimensioni del file di registro di controllo.
. Selezionare l'opzione *Invia registri di controllo al server Syslog* se si sceglie di inviare i registri al server syslog. Immettere i dettagli del server.
. Salvare le impostazioni.

