---
permalink: scv60_releasenotes_60_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.0, 6.0.1' 
summary: Scopri le nuove funzionalità disponibili nel plug-in SnapCenter per VMware vSphere 6,0. 
---
= Novità del plug-in SnapCenter per VMware vSphere 6,0
:allow-uri-read: 


[cols="30%,70%"]
|===
| Aggiornare | Descrizione 


 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_concepts_overview.html["Supporto del protocollo NVMe over TCP"]
 a| 
Il plug-in SnapCenter per VMware vSphere 6,0 ora supporta il protocollo NVMe over TCP per datastore VMFS.

Non serve hardware aggiuntivo per l'implementazione del protocollo NVMe over TCP, che lo rende più semplice e conveniente per te.

Come iSCSI, i datastore VMFS con protocollo NVMe over TCP possono utilizzare qualsiasi NIC e switch ethernet e supportare tutte le operazioni standard, come backup, ripristino, montaggio, collegamento e scollegamento.



 a| 
https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_create_backup_policies_for_vms_and_datastores.html["Supporto per la sincronizzazione attiva di SnapMirror"]
 a| 
Ora puoi utilizzare il plug-in SnapCenter per VMware vSphere per configurare le funzionalità di sincronizzazione attive di SnapMirror, come RPO (Zero Recovery Point Objective), RTO (Recovery Time Objective) e failover trasparente delle applicazioni.

La sincronizzazione attiva di SnapMirror è supportata solo per gli archivi dati VMFS.

|===