---
permalink: scv_rn_upgrade_paths.html 
sidebar: sidebar 
keywords: upgrade paths, scv, 6.1 
summary: Scopri le nuove funzionalità disponibili nel plug-in SnapCenter per VMware vSphere 6,1. 
---
= Percorsi di aggiornamento
:allow-uri-read: 


[role="lead"]
La versione del plug-in SnapCenter per VMware vSphere (SCV) alla quale è possibile eseguire l'aggiornamento dipende dalla versione attualmente in uso.

[NOTE]
====
L'aggiornamento al plug-in SnapCenter per VMware vSphere (SCV) 4,8 e versioni successive è supportato solo su VMware vCenter server 7 update 1 e versioni successive. Per il server VMware vCenter precedente alla versione 7 aggiornamento 1, è necessario continuare a utilizzare SCV 4,7.

====
[cols="50%,50%"]
|===
| Se si utilizza la versione SCV… | È possibile aggiornare SCV direttamente a… 


 a| 
DISTRIBUTORE IDRAULICO 6,0
 a| 
SCV 6,1



 a| 
DISTRIBUTORE IDRAULICO 5,0
 a| 
Distributori idraulici 6,0 e 6,1



 a| 
DISTRIBUTORE IDRAULICO 4,9
 a| 
Distributori idraulici 5,0 e 6,0



 a| 
DISTRIBUTORE IDRAULICO 4,8
 a| 
Distributori idraulici 4,9 e 5,0



 a| 
DISTRIBUTORE IDRAULICO 4,7
 a| 
Distributori idraulici 4,8 e 4,9

|===
Per i database virtualizzati e i file system integrati con SnapCenter, questo è il percorso di aggiornamento:

[cols="30%,30%,40%"]
|===
| Se si utilizza | Se il plug-in VMware è... | È possibile eseguire direttamente l'aggiornamento a... 


 a| 
SnapCenter 6,1
 a| 
DISTRIBUTORE IDRAULICO 6,0
 a| 
SCV 6,1



 a| 
SnapCenter 6,0
 a| 
DISTRIBUTORE IDRAULICO 5,0
 a| 
DISTRIBUTORE IDRAULICO 6,0



 a| 
SnapCenter 5,0
 a| 
DISTRIBUTORE IDRAULICO 4,9
 a| 
DISTRIBUTORE IDRAULICO 5,0



 a| 
SnapCenter 4,9
 a| 
DISTRIBUTORE IDRAULICO 4,8
 a| 
DISTRIBUTORE IDRAULICO 4,9



 a| 
SnapCenter 4,8
 a| 
DISTRIBUTORE IDRAULICO 4,7
 a| 
DISTRIBUTORE IDRAULICO 4,8

|===
Per informazioni aggiornate sulle versioni supportate, fare riferimento a https://imt.netapp.com/matrix/imt.jsp?components=121034;&solution=1517&isHWU&src=IMT["Tool di matrice di interoperabilità NetApp"^] (IMT).
