---
permalink: scv_releasenotes_whats_new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, scv, 6.2' 
summary: Scopri le nuove funzionalità disponibili nel SnapCenter Plug-in for VMware vSphere 6.2. 
---
= Novità del SnapCenter Plug-in for VMware vSphere 6.2
:allow-uri-read: 


[role="lead"]
Scopri le nuove funzionalità disponibili nel SnapCenter Plug-in for VMware vSphere 6.2.

Il SnapCenter Plug-in for VMware vSphere 6.2 aggiunge il supporto per il backup e il ripristino di macchine virtuali (VM) su datastore VMFS per sistemi ASA r2 che eseguono ONTAP 9.17.1 o versioni successive.  Con questa versione, è possibile eseguire le seguenti operazioni per VM, datastore e formato Virtual Machine Disk (VMDK) sui sistemi ASA r2:

* Fornire gruppi di coerenza per la protezione primaria
* Eseguire backup basati su gruppi di coerenza
* Utilizzare gruppi di coerenza gerarchica (disponibili con ONTAP 9.17.1 e versioni successive)
* Eseguire flussi di lavoro di clonazione
* Eseguire flussi di lavoro di ripristino
* Fornisce protezione secondaria durante la creazione o la modifica di gruppi di risorse (disponibile con ONTAP 9.16.1 e versioni successive)

